import {DeviceService} from "../../../../common/src/service/device-service";
import {SerializerService} from "../../../../common/src/service/serializer-service";
import {ChromeApiPlatform} from "../../../../common/src/browser/api/platform/chrome-api-platform";
import {BrowserService} from "../../../../common/src/service/browser-service";
import {LanguageService} from "../../../../common/src/service/language-service";
import {LocalStoragePlatform} from "../../../../common/src/storage/local-storage-platform";
import {container} from "../../../../common/src/ioc/container";
import {ThemeService} from "../../../../common/src/service/theme-service";
import {SafariApiPlatform} from "../../../../common/src/browser/api/platform/safari-api-platform";
import {RuntimeStoragePlatform} from "../../../../common/src/storage/runtime-storage-platform";
import {StorageService} from "../../../../common/src/service/storage-service";
import {ContextService} from "../../../../common/src/service/context-service";
import {ErrorHandler} from "../../../../common/src/handler/error-handler";
import {SentryService} from "../../../../common/src/service/sentry-service";
import {NotificationService} from "../../../../common/src/service/notification-service";
import {LocationService} from "../../../../common/src/service/location-service";
import {SecurityService} from "../../../../common/src/service/security-service";
import {UserService} from "../../../../common/src/service/user-service";
import {UserClient} from "../../../../common/src/client/user-client";
import {AxiosService} from "../../../../common/src/service/axios-service";
import {UserOverviewSerializer} from "../../../../common/src/serializer/overview/user-overview-serializer";
import {UserSerializer} from "../../../../common/src/serializer/user-serializer";
import {LanguageSerializer} from "../../../../common/src/serializer/language-serializer";
import {UserLanguageReferenceSerializer} from "../../../../common/src/serializer/user-language-reference-serializer";
import {UserSubscriptionSerializer} from "../../../../common/src/serializer/user-subscription-serializer";
import {InternalEventService} from "../../../../common/src/service/internal-event-service";
import {SecurityClient} from "../../../../common/src/client/security-client";
import {TokenService} from "../../../../common/src/service/token-service";
import {AluneaDomService} from "../../../../common/src/service/alunea-dom-service";
import {PlatformService} from "../../../../common/src/service/platform-service";
import {RouterService} from "../../../../common/src/service/router-service";

const deviceService = new DeviceService();
const chromeApiPlatform = new ChromeApiPlatform();
const safariApiPlatform = new SafariApiPlatform();
const browserService = new BrowserService(chromeApiPlatform, safariApiPlatform, deviceService);
const serializerService = new SerializerService();
const localStoragePlatform = new LocalStoragePlatform(serializerService);
const runtimeStoragePlatform = new RuntimeStoragePlatform(browserService, serializerService);
const storageService = new StorageService(runtimeStoragePlatform, localStoragePlatform, browserService);
const themeService = new ThemeService(storageService);
const languageService = new LanguageService();
const contextService = new ContextService();
const notificationService = new NotificationService();
const axiosService = new AxiosService(import.meta.env.VITE_API_URL, notificationService, contextService);
const languageSerializer = new LanguageSerializer();
const userSerializer = new UserSerializer(languageSerializer);
const userLanguageReferenceSerializer = new UserLanguageReferenceSerializer(languageSerializer);
const userSubscriptionSerializer = new UserSubscriptionSerializer();
const userOverviewSerializer = new UserOverviewSerializer(
    userSerializer,
    userLanguageReferenceSerializer,
    userSubscriptionSerializer
);
const userClient = new UserClient(axiosService, userOverviewSerializer);
const internalEventService = new InternalEventService();
const userService = new UserService(userClient, internalEventService);
const securityClient = new SecurityClient(axiosService);
const tokenService = new TokenService();
const securityService = new SecurityService(storageService, userService, securityClient, tokenService, internalEventService);
const locationService = new LocationService();
const sentryService = new SentryService(locationService, contextService, securityService);
const errorHandler = new ErrorHandler(notificationService, sentryService);
const aluneaDom = new AluneaDomService();
const platformService = new PlatformService();
const routerService = new RouterService();

platformService.setBrowserService(browserService);

container.set(deviceService);
container.set(chromeApiPlatform);
container.set(safariApiPlatform);
container.set(browserService);
container.set(serializerService);
container.set(localStoragePlatform);
container.set(runtimeStoragePlatform);
container.set(storageService);
container.set(themeService);
container.set(languageService);
container.set(contextService);
container.set(notificationService);
container.set(axiosService);
container.set(languageSerializer);
container.set(userSerializer);
container.set(userLanguageReferenceSerializer);
container.set(userSubscriptionSerializer);
container.set(userOverviewSerializer);
container.set(userClient);
container.set(internalEventService);
container.set(userService);
container.set(securityClient);
container.set(tokenService);
container.set(securityService);
container.set(locationService);
container.set(sentryService);
container.set(errorHandler);
container.set(aluneaDom);
container.set(platformService);
container.set(routerService);

export { container };